repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.8
  hooks:
  - id: ruff
    args: [--fix]
    exclude: ^workers/consumer\.py$
  - id: ruff-format
    exclude: ^(workers/consumer\.py|core_wms/app/tasks/registry\.py)$